config/routes.rb
Rails.application.routes.draw do


 get 'backend/home'
 get 'backend/menu'
root 'main#home'
get 'search/alltime', to: 'main#alltime', as: :alltime_search
get 'search/lastmonth', to: 'main#lastmonth', as: :lastmonth_search
get 'search/lastweek', to: 'main#lastweek', as: :lastweek_search
get 'search', to: 'main#search', as: :search
get 'archive', to: 'main#archive', as: :archive
resources :notices, except: [:index, :new]
resources :sessions, only: [:new, :create, :destroy]
get 'searchresults', to: 'main#searchresults'
get 'addreport/:notice_id/:admin_id/:zetype', to: 'reports#add', as: :add_report
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
has_many :reports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
class Notice < ApplicationRecord
validates :title, presence: { message: "%{model} needs a %{attribute}" }
validate :picturebody
has_one_attached :descpic
validates :descpic, blob: { content_type: :image }
has_many :reports
private 
def picturebody
	if body.blank? && descpic.attached?
	errors[:body] << "Notice text can't be blank if a picture is attached."
	end
end
end

app/models/report.rb
class Report < ApplicationRecord
belongs_to :admin
belongs_to :notice


def unique_in_notice
Report.each do |t|
if notice_id == t.notice_id && zetype == t.zetype && admin_id == t.admin_id
errors[:base] << "Report cannot share a notice and a type"
end
end
end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def login
	admin = Admin.where(username: params[:username])
	if admin && admin.authenticate(params[:password])
	session[:admin] = admin.id
	redirect_to admin_admin_path
	else
	redirect_to root_path
	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController

before_action :logdin, only: [:menu]  
def home
  end

  def menu
	@theadmin = Admin.find(session[:admin].to_i)
	@notices = Notice.all
  end

private 

def logdin
	if session[:admin].present?
	return true
	else
	redirect_to backend_home_path
	end
end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
before_action :setnewnotice, only: [:home]
before_action :setnotices, only: [:archive, :alltime]
def archive
end
def hotnotices
end
def search
end
def searchresults
if params.has_key?(:title) && params.has_key?(:notecategory) && !params[:notecategory].blank?
@searchresults = Notice.where("(title like ? OR title like ?) AND notecategory like ?", "%#{params[:title]}%", "%#{params[:title]}.strip%", "%#{params[:notecategory]}%")
elsif params.has_key?(:title) && params.has_key?(:notecategory) && params[:notecategory].blank?
@searchresults = Notice.where("title like ? OR title like ?", "%#{params[:title]}%", "%#{params[:title]}.strip%")
end
respond_to do |f|
	f.js
end
end
def alltime
respond_to do |f|
	f.json { render json: @allnotices }
end
end
def lastmonth
@monthnotices = Notice.where("created_at >= ?", Date.today - 1.month)
respond_to do |f|
	f.json { render json: @monthnotices }
end
end
def lastweek
@weeknotices = Notice.where("created_at >= ?", Date.today - 1.week)
respond_to do |f|
	f.json { render json: @weeknotices }

end
end 
def last3
@zestring = params[:zeform]
@zelength = params[:zeformlength]
respond_to do |f|
	f.js
end
end
private
def setnotices
@allnotices = Notice.all
end
def setnewnotice
@notice = Notice.new
end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
def create
	@notice = Notice.create(notice_params)
	respond_to do |f|
		if @notice.save
			f.html { redirect_back fallback_location: root_path }
			f.js
		else	
			f.html { render 'main/home' }
		end
	end
end



def show
	@thenotice = Notice.find(params[:id])
end

def destroy
	@notice = Notice.find(params[:id])
	@notice.destroy
	
	redirect_to backend_menu_path
end

private
	def notice_params
		params.require(:notice).permit(:title, :body, :notecategory, :descpic)
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
def add
@thenotice = Notice.find(params[:notice_id].to_i)
@theadmin = Admin.find(params[:admin_id].to_i)
@thetype = params[:zetype]

@thereport = Report.where(notice_id: @thenotice.id, admin_id: @theadmin.id, zetype: @thetype).first_or_create!(reported: false)
@thereport.toggle!(:reported)

end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	admin = Admin.where(username: params[:username]).first
	if admin && admin.authenticate(params[:password])
	session[:admin] = admin.id
	redirect_to backend_menu_path
	else
	redirect_to backend_home_path
	end
  end

  def destroy
	session[:admin] = nil
	redirect_to root_path
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend_helper.rb
module BackendHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/backend/_backnotice.html.erb
<div id = "notice-<%= backnotice.id %>">
<span class = "backtext"><%= backnotice.title %></span> | 
<span class = "backtext"><%= link_to "Show", notice_path(backnotice) %></span> | 
<span class = "backtext"><%= link_to "Destroy", notice_path(backnotice), method: :delete %></span><b>
<div class = "hold-reports">
<% ["Obscene", "Abuse", "Illegal"].each do |t| %>
<%= link_to add_report_path(backnotice, @theadmin, t), remote: true do %>
<% if backnotice.reports.where(admin_id: @theadmin.id, reported: true, zetype: t).any? %>
<div class = "report-button <%= t %> <%= t %>-report"></div>
<% else %> 
<div class = "report-button <%= t %> <%= t %>-unreported"></div>
<% end %>
<% end %>
<% end %>
</div>
</div>

app/views/backend/home.html.erb
<%= form_with url: sessions_path do |f| %>
	<%= f.label :username, "Enter Username" %>
	<%= f.text_field :username %>
	<%= f.label :password, "Enter password" %>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>

app/views/backend/menu.html.erb
<%= render partial: "backnotice", collection: @notices %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticeboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div class = "titlebox"><h1>Hello Admin!</h1></div>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticeboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

<body>

<div class = "titlebox">
<h1>Noticeboard</h1>
<p></p>
<div id = "bigoldbox">
<div class = "menubox">
<div class = "tabbox toptabbox">Header</div>
<div class = "tabbox">Item 1</div>
<div class = "tabbox">Item 2</div>
<div class = "tabbox">Item 3</div>
<%= link_to search_path do %>
<div class = "tabbox">Search</div>
<% end %>
</div>
<div class = "menubox">
<div class = "tabbox toptabbox">Header 2</div>
<%= link_to search_path do %>
<div class = "tabbox">Search it up</div>
<% end %>
<div class = "tabbox">Item 5</div>
<div class = "tabbox">Item 6</div>
</div>
</div>
</div>

<%= link_to root_path do %>
<div class = "navbox"><span class = "navtext">Home</span></div>
<% end %>
<%= link_to archive_path do %>
<div class = "navbox"><span class = "navtext">Archive</span></div>
<% end %>


    <%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticeboard: Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

 <body>
<div class = "titlebox"><h1>Hello Admin!</h1></div>
<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/main/_searchform.html.erb
<%= form_tag("/search", method: :get, id: "searchform") do %>
	<%= label_tag(:title, "Search for notices") %>
	<%= text_field_tag(:title) %><br>
	
	<%= label_tag(:notecategory, "Notice type") %>
	<%= select_tag(:notecategory, options_for_select([['Any', ''], 'Announcement', 'Sale', 'Personal', 'Warning'])) %>
	

<% end %>

app/views/main/_timeresults.html.erb
<div class = "underbox">
<%= link_to alltime_search_path do %>
<div class = "navbox"><span class = "navtext">All time</span></div>
<% end %>
<%= link_to lastweek_search_path do %>
<div class = "navbox"><span class = "navtext">Last week</span></div>
<% end %>
<%= link_to lastmonth_search_path do %>
<div class = "navbox"><span class = "navtext">Last month</span></div>
<% end %>
</div>

app/views/main/alltime.html.erb
<%= render partial: 'timeresults' %>
<%= render(@allnotices) || "No results" %>

app/views/main/archive.html.erb
<%= render @allnotices %>

app/views/main/home.html.erb
<%= render "notices/form" %>
<div id = "timecontainerbox">
<div id = "firsttab" class = "timebox">Notices All Time</div>
<div id = "weeknotices" class = "timebox">Notices Last Week</div>
<div id = "monthnotices" class = "timebox">Notices Last Month</div>
</div>
<div id = "answerbox"></div>

app/views/main/last3.js.erb
$('#returnbox').html('');
$('#returnbox').prepend('<%= @zestring %><br><%= @zelength %>');
$('.notice').hide().fadeIn(700);

app/views/main/lastmonth.html.erb
<%= render partial: 'timeresults' %>
<%= render(@monthnotices) || "No results" %>

app/views/main/lastweek.html.erb
<%= render partial: 'timeresults' %>
<%= render(@weeknotices) || "No results" %>

app/views/main/search.html.erb
<%= render partial: 'main/searchform' %>
<div id = "returnbox"></div>

app/views/main/searchresults.js.erb
$zereturn = $('#returnbox');
$zereturn.html('');
$zereturn.prepend('<%= escape_javascript(render @searchresults) %>');

app/views/notices/_form.html.erb
<div class = "holdform">
<%= form_with(model: @notice) do |f| %>

<% if @notice.errors.any? %>
	<% @notice.errors[:title].each do |msg| %>
		<%= msg %><br>
	<% end %>
	<% @notice.errors[:body].each do |msg| %>
		<%= msg %><br>
	<% end %>
<% end %>

<p>
	<%= f.label :title, "Notice title" %><br>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :body, "Notice text" %><br>
	<%= f.text_area :body %>
</p>

<p>
	<%= f.label :notecategory, "What is your notice type?" %><br>
	<%= f.select(:notecategory, [['Any', nil],'Announcement', 'Sale', 'Personal','Warning']) %>
</p>

<p>
	<%= f.label :descpic, "Upload a picture for your notice (optional)" %><br>
	<%= f.file_field(:descpic) %>
</p>
<p>
	<%= f.submit "Submit Notice" %>
</p>
<% end %> 
</div>

app/views/notices/_notice.html.erb
<% @body = simple_format(notice.body) %>
<div class = "notice">
<h1><%= notice.title %></h1><br>
<% if notice.body.present? %>
<p><%= @body %></p>
<% else %>
<p>The user hasn't entered any text for this notice</p>
<% end %>
<% if notice.descpic.attached? %>
<%= image_tag notice.descpic %>
<% end %>
</div>

app/views/notices/create.js.erb
$(".holdform").after("<%= escape_javascript(render @notice) %>");
$(".notice").hide().fadeIn(700);

app/views/notices/show.html.erb
<%= render @thenotice %>